### ISSUE TITLE
keyboard file does not add a space and comma with multiple layouts

### ISSUE THREAD

**Issue by leonzwrx** [Sunderland93/sway-input-config#7]
When keyboard config file is generated - when there are 2 keyboards set (one with a variant and one without, it does not add a space). For instance here's mine:

input "type:keyboard" {
  xkb_layout us,ru
  xkb_variant phonetic_winkeys
  xkb_options grp:alt_shift_toggle
  xkb_model pc105
  repeat_delay 300
  repeat_rate 40
  xkb_capslock disabled
  xkb_numlock disabled
}

In this case, russian keyboard will not see the phonetic_winkeys layout until a space and a comma is added. See below for a working config:

input "type:keyboard" {
  xkb_layout us,ru
  xkb_variant  ,phonetic_winkeys
  xkb_options grp:alt_shift_toggle
  xkb_model pc105
  repeat_delay 300
  repeat_rate 40
  xkb_capslock disabled
  xkb_numlock disabled
}

**Comment by Sunderland93** [comment]
Hello. Please post your ~/.config/sway-input-config/settings.json

**Comment by leonzwrx** [comment]
> Hello. Please post your ~/.config/sway-input-config/settings.json

Here you go:
https://raw.githubusercontent.com/leonzwrx/dotfiles/master/.config/sway-input-config/settings

**Comment by Sunderland93** [comment]
Please check https://github.com/Sunderland93/sway-input-config/pull/8 if that helps

**Comment by leonzwrx** [comment]
Thanks!
